server:
  port: "8080"
  timeout: 60

database:
  host: "172.31.236.79"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "event_platform"
  sslmode: "disable"

auth:
  jwt_secret: "mKgUM8ue5v8BmvHAQU1PA4MvDwpkBXqelFEQYYIUdOg5kzav8haoh86aSvyOhdHRvOHgwbBmla3QD4sTV2Qy8Hs1OQ6tgduC0fverADHp0LtyKodjx4T5xoaeVCvcDVy7fK1VGDviePC04osrcMXR2sof4MKFp8ujwBKk3z9iv5vzAvvlyWp9ROV17bfoWaE54EYP7c1ZrXc1rbt816Oe8grvZ6qwVUeWZEtfGvBqLOhwpAXfFoVoOSxYPVLMs3fekqD6CSQ7tpglZ6OLPCfQcJTfZ68z0X0ymbX8T3m6FrsdqZk25HG48xJDiisJL0oZ0YeqX8Q7zMw8aTvhpsMq3qV5tlCgFkHBmHl0LEtZPBub9kHvyDGv1QCmYwOzR9IJtLZCbeWyS7eJIo8OE7bbm0slOlKgWCFXb9iise9FtvpxKb5mtPoz84mbmX0iDyq9S4EVRuw6QrmlmE8vTxYgcBXl71ZrPQzPYmia9d6Pb7mq7FVbtcab7xu9MZyO8AH"
  token_expiry_hrs: 24